<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitae810e8f36270efa2dfc886965c6dd66
{
    public static $files = array (
        'faf8af8c659e00ec8a09b88428ebe991' => __DIR__ . '/../..' . '/includes/constants.php',
        '5dfaf1b9c09a11c935bc021a6c07d9b7' => __DIR__ . '/../..' . '/includes/functions.php',
        '57f529d837218c2ad2462fb42a5f92e8' => __DIR__ . '/../..' . '/includes/database.php',
        '3b29600eb506170dae185f7e84f5e94f' => __DIR__ . '/../..' . '/includes/booking-processor.php',
        '07918a42ab40e19912788db0b84e0f66' => __DIR__ . '/../..' . '/includes/integrations/ga4.php',
        '57aea7b6c32c86d680223c531d02b063' => __DIR__ . '/../..' . '/includes/integrations/gtm.php',
        'd09fa0872187d66401e1b93abfc9d2a8' => __DIR__ . '/../..' . '/includes/integrations/facebook.php',
        '53e6eb3f2e8b8d709b0ca83eefdbca23' => __DIR__ . '/../..' . '/includes/integrations/brevo.php',
        '7f522dc8504fe46676c5ffcbcdcd9478' => __DIR__ . '/../..' . '/includes/api/webhook.php',
        '7ff7af685187cccf521bd90b214d6172' => __DIR__ . '/../..' . '/includes/api/polling.php',
        '788021ba160f568ab1bbd0d929f73c9d' => __DIR__ . '/../..' . '/includes/cli.php',
    );

    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'FpHic\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'FpHic\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitae810e8f36270efa2dfc886965c6dd66::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitae810e8f36270efa2dfc886965c6dd66::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitae810e8f36270efa2dfc886965c6dd66::$classMap;

        }, null, ClassLoader::class);
    }
}
