<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'faf8af8c659e00ec8a09b88428ebe991' => $baseDir . '/includes/constants.php',
    '5dfaf1b9c09a11c935bc021a6c07d9b7' => $baseDir . '/includes/functions.php',
    '57f529d837218c2ad2462fb42a5f92e8' => $baseDir . '/includes/database.php',
    '3b29600eb506170dae185f7e84f5e94f' => $baseDir . '/includes/booking-processor.php',
    '07918a42ab40e19912788db0b84e0f66' => $baseDir . '/includes/integrations/ga4.php',
    '57aea7b6c32c86d680223c531d02b063' => $baseDir . '/includes/integrations/gtm.php',
    'd09fa0872187d66401e1b93abfc9d2a8' => $baseDir . '/includes/integrations/facebook.php',
    '53e6eb3f2e8b8d709b0ca83eefdbca23' => $baseDir . '/includes/integrations/brevo.php',
    '7f522dc8504fe46676c5ffcbcdcd9478' => $baseDir . '/includes/api/webhook.php',
    '7ff7af685187cccf521bd90b214d6172' => $baseDir . '/includes/api/polling.php',
    '788021ba160f568ab1bbd0d929f73c9d' => $baseDir . '/includes/cli.php',
);
